basic:
    name: 'Mrs. Esther Jacobi III'
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - 'https://www.gusikowski.com/modi-maxime-dolor-alias-iusto-velit.html'
        - 'https://www.damore.com/et-nostrum-maiores-aut-adipisci'
    monitoring:
        days: {  }
        type: ''
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
